### ISSUE TITLE
Cookie header

### ISSUE THREAD

**Issue by millette** [rainbowintheshell/node-diaspora#4]
I noticed two identical cookie headers while I was adding image support. I didn't add the cookie header to the image post function because I believe request.jar() (this.j) takes care of it. I also removed it from my refactoring of postStatusMessage() - well _postStatusMessage() in my case.

I think the cookie header could be removed from everywhere, if I understand correctly.

**Comment by aranciaga** [comment]
You probably be right, I'll check it.
