### ISSUE TITLE
Add support for multiple aspects

### ISSUE THREAD

**Issue by millette** [rainbowintheshell/node-diaspora#5]
Unless I missed something, I don't think the current implementation supports multiple aspects when posting a status.

I'm building on node-diaspora and twitter modules for https://gitlab.com/facil/garrocheur and I could really use multiple aspects supports. I will probably submit a patch later (within a week or so).

**Comment by aranciaga** [comment]
You are right. I will wait for your patch millete. Thanks a lot for your contributions!

**Comment by millette** [comment]
Got distracted... can you leave the issue open as a reminder? Thanks.
